### ISSUE TITLE
GZ1_Check Problem with check = 10

### ISSUE THREAD

**Issue by itzdvl** [EszopiCoder/google-barcode-fx-library#1]
![image](https://github.com/EszopiCoder/google-barcode-fx-library/assets/5459119/e4970009-abf0-469a-af53-4fdd23a5f452)

Hello, great library you have going here.  Wanted to point out a typo in the function GZ1_Check of Main.gs.  Looks like there is one too many equal signs.  I corrected and tested on my local copy and all looks good after changing the comparison operator to assignment.

**Comment by EszopiCoder** [comment]
Thank you for catching that! It has been updated.
